"""add revenue to trips

Revision ID: 8a84de1870fb
Revises: b3d0169a1cc6
Create Date: 2026-07-12 16:55:00.088265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a84de1870fb'
down_revision: Union[str, Sequence[str], None] = 'b3d0169a1cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('revenue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'revenue')
    # ### end Alembic commands ###
